# Generated by Django 4.1.1 on 2022-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foodies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date published")),
                ("food_name", models.CharField(max_length=200)),
                ("calories", models.IntegerField(default=0)),
                ("carbohydrates", models.IntegerField(default=0)),
                ("cholesterol", models.IntegerField(default=0)),
                ("saturated_fat", models.IntegerField(default=0)),
                ("total_fat", models.IntegerField(default=0)),
                ("fiber_content", models.IntegerField(default=0)),
                ("potassium", models.IntegerField(default=0)),
                ("protein", models.IntegerField(default=0)),
                ("sodium", models.IntegerField(default=0)),
                ("sugar", models.IntegerField(default=0)),
            ],
        ),
    ]
