# Generated by Django 4.1.1 on 2022-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="foodies", name="calories",),
        migrations.AddField(
            model_name="foodies",
            name="serving_size",
            field=models.IntegerField(default=100),
        ),
    ]
