# Generated by Django 4.1.1 on 2022-09-14 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0003_foodies_calories"),
    ]

    operations = [
        migrations.RemoveField(model_name="foodies", name="date",),
        migrations.AddField(
            model_name="foodies",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
