# Generated by Django 4.1.1 on 2022-09-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0004_remove_foodies_date_foodies_create_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodies", old_name="create_date", new_name="created_date",
        ),
    ]
